---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-api
        image: cr.yandex/crpg2dlmju6tcmkcnb0l/todo:latest
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: 0.5
            memory: "200Mi"
          requests:
            cpu: 0.3
            memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001

---      
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: todo-ingress
  namespace: todo
spec:
  rules:
    - host: todo.com
      http:
        paths:
          - backend:
              serviceName: todo-app-service
              servicePort: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  # tls:
  #     - hosts:
  #         - www.example.com
  #       secretName: example-tls